name: 'Lint Code'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: |
          # Lint all .py files recursively
          # Adjust the directory as needed for your project
          find . -name "*.py" -exec flake8 {} +
          echo "Successfully linted all Python files."

  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install JSHint
        run: npm install --global jshint

      - name: Run JSHint
        run: |
          # Lint all .js files recursively
          # Adjust the directory path to wherever your .js files live
          find ./server/database -name "*.js" -exec jshint {} +
          echo "Successfully linted all JavaScript files."
